# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

# Disable codegen for old architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '0'
ENV['USE_CODEGEN'] = '0'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# Force MapboxMaps 10.x for compatibility with @rnmapbox/maps 10.2.7
$RNMapboxMapsVersion = '~> 10.19.0'

pre_install do |installer|
  $RNMapboxMaps.pre_install(installer)
end

target 'HeimursagaMobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    # Use old architecture
    :fabric_enabled => false
  )

  target 'HeimursagaMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)

    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix deployment target and React Native header search paths
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'

        # Fix header search paths for React Native 0.75.x
        # This resolves issues with yoga and bridging headers
        react_native_path = "$(PODS_ROOT)/../../node_modules/react-native"

        if target.name == 'Yoga'
          config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"#{react_native_path}/ReactCommon/yoga\" "
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"#{react_native_path}/ReactCommon\" "
        end

        # Fix for React-bridging and TurboModule headers
        if target.name.start_with?('React')
          config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"#{react_native_path}/ReactCommon\" "
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"#{react_native_path}/ReactCommon/react/bridging\" "
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"#{react_native_path}/ReactCommon/react/nativemodule/core\" "
          config.build_settings['HEADER_SEARCH_PATHS'] << "\"#{react_native_path}/ReactCommon/yoga\" "
        end
      end
    end
  end
end
